config/routes.rb
Rails.application.routes.draw do

  get "remove_follower" => "home#unfollow_politician", as: "unfollow_politician"
  get "new_follower" => "home#follow_politician", as: "follow_politician"
  get "search" => "searches#index"
  post "searches" => "searches#index", as: "search_rep"
  root 'home#signin'
  get "index" => "home#index", as: "index" 

  devise_for :users, controllers: { registrations: "registrations"}

end

app/models/politician.rb
class Politician < ActiveRecord::Base
end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  serialize :politicians_following, Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	require 'unirest'
	require 'congress'

	def signin
	  	if user_signed_in?
	  		redirect_to index_path
	  	else
	  		redirect_to new_user_session_path
	  	end 
	end

	def index
		@time = Time.new
		@todays_date = ((@time.year)).to_s + "-" + ((@time.month-2)).to_s + "-" +@time.day.to_s
		puts @todays_date

		@user = current_user
		@politicians_following = @user.politicians_following
		@congress = Congress::Client.new('5b435d0bb1f946168564c8398f0ccc5e')
		@politician_arr = []

		@politicians_following.each do |x|
			@rep = Politician.find_by(bioguide_id: x)
			@politician_arr.push(@rep)
		end

		@resp_arr = []
		@politician_arr.each do |x|
			@bioguide_id = x.bioguide_id

			@response = Unirest.get "http://capitolwords.org/api/1/text.json?bioguide_id="+@bioguide_id+"&start_date="+ @todays_date +"&apikey=5b435d0bb1f946168564c8398f0ccc5e",
			headers:{ "Accept" => "application/json"}
			@resp_arr.push(@response.body['results'])
		end

		# @user.politicians_following.each do |politician|
		# 	@response = Unirest.get "http://capitolwords.org/api/1/text.json?bioguide_id=S000033&apikey=5b435d0bb1f946168564c8398f0ccc5e",
		# 	headers:{ "Accept" => "application/json" }
		# end

		# @response = Unirest.get "http://capitolwords.org/api/1/text.json?bioguide_id=S000033&apikey=5b435d0bb1f946168564c8398f0ccc5e",
		# 	headers:{ "Accept" => "application/json" }
	end

	def follow_politician
		@user = current_user
		@new_politician_id = params[:bioguide_id]

		if @user.politicians_following.index(@new_politician_id) == nil
			@user.politicians_following << @new_politician_id
		end

		@rep = Politician.find_by(bioguide_id: @new_politician_id)
		if @rep.nil?
				@congress = Congress::Client.new('5b435d0bb1f946168564c8398f0ccc5e')
				@rep_info = @congress.legislators(bioguide_id: @new_politician_id)['results'].first
				@full_name = @rep_info['first_name'] + " " + @rep_info['last_name']
				@new_politician = Politician.create(name: @full_name, bioguide_id: @rep_info['bioguide_id'])
		end

		@user.save

		redirect_to root_path
	end

	def unfollow_politician
		@user = current_user
		@politician_id = params[:bioguide_id]

		@user.politicians_following.delete(@politician_id)
		@user.save

		redirect_to root_path
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

	def account_update_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
	end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

	def index
		@user = current_user
		@searched = params[:name]
		@congress = Congress::Client.new('5b435d0bb1f946168564c8398f0ccc5e')

		#Into here I need to include the Congress gem to make the search get relevant info
		#Eventually this should search for companies too
		#The resulting view will be a list of all results. Clicking on the results will give you the option of "following" that rep

		if /\A\d+{5}\z/.match(@searched)
		 	#regex checks if search is a zip code
		 	@result = []
		 	@response = @congress.legislators_locate(@searched)['results']

		 	@response.each do |x|
			 	if @user.politicians_following.index(x['bioguide_id']) == nil
						x['following?'] = false
					else
						x['following?'] = true
				end
  				@result.push(x)
  			end
  		else #if not a 5-digit zip code
  			@result = []
  			@response = @congress.legislators(:query => @searched)['results']

  			@response.each do |x|
  				#This adds the following? value to determine if "Follow" or "Unfollow" button should appear
  				if @user.politicians_following.index(x['bioguide_id']) == nil
					x['following?'] = false
				else
					x['following?'] = true
				end
  				@result.push(x)
  			end

  		end  
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/home/index.html.erb
<%= form_tag("/search", method: "get")  do %>
<%= label_tag(:name, "Search for:") %>
<%= text_field_tag :name %>
<%= submit_tag("Search")%>
<% end %>


<% @resp_arr.each do |politician| %>
	<% politician.each do |record| %>
	<% @speaker_name = record["speaker_first"] + " " + record["speaker_last"] %>
	<% @link = record["capitolwords_url"] %>
			<% record['speaking'].each do |text| %>
			<p><%= link_to text, @link %> <br>-<%=@speaker_name%></p>
			<% end %>
		<% end %>
<% end %>

<!-- <ul>
<#% @resp_arr.each do |x| %>
	<li>
	<#%= x['results'][0]['speaking'] %>
	<#%= x['results'][0]['speaker_first']%> <%#=x['results'][0]['speaker_last'] %>
	</li>
<#% end %>
</ul> -->
<!-- <#% @resp_arr.each do |x| %>
	<p><#%= x %></p>
<#% end %> -->
<!-- 
<#%= @response.body['results'].each do |x| %>
	<#% @link = x["capitolwords_url"] %>
	<#% @speaker_name = x["speaker_first"] + " " + x["speaker_last"] %>
	<#% x["speaking"].each do |i|%>
		<p><#%= link_to i, @link %> <br>-<#%=@speaker_name%></p>
	<#% end %>
<#% end %> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RepBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
	<p>Hello, <%= current_user.name %> - <%= link_to "Sign Out", destroy_user_session_path, :method => "delete" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/searches/index.html.erb
<%= link_to('Home', root_path)%>
<br>
<%= form_tag("/search", method: "get")  do %>
<%= label_tag(:name, "Search for:") %>
<%= text_field_tag :name %>
<%= submit_tag("Search")%>
<% end %>
<br>
Searched for: 
<ul>
<% @result.each do |x| %>
<li>
<%= x['first_name'] %>
<%= x['last_name'] %>
<%= link_to("View site", x['website']) %>
<%= link_to("Twitter", "http://www.twitter.com/" + x['twitter_id']) if x['twitter_id'] %>
<%= link_to("Youtube", "http://www.youtube.com/" + x['youtube_id']) if x['youtube_id']%>
<%= link_to("Facebook", "http://www.facebook.com/" + x['facebook_id']) if x['facebook_id']%>
<%= link_to("Contact", x['contact_form']) if x['contact_form']%>
	<% if x['following?'] == true %>
	<%= link_to("Unfollow", unfollow_politician_path(bioguide_id: x['bioguide_id'])) %>
	<% else %>
	<%= link_to("Follow", follow_politician_path(bioguide_id: x['bioguide_id'])) %>
	<!-- Should eventually build an unfollow path and direct to that-->
	<% end %>
</li>
<% end %>
</ul>